version: "3"
services:
  db:
    container_name: h2
    image: oscarfonts/h2:latest
    ports:
      - 1521:1521
      - 8081:81
    environment:
      H2_OPTIONS: -ifNotExists
    volumes:
      - ./h2/:/opt/h2-data
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: compose-test
    depends_on:
      - db
    ports:
      - 8080:8080
#    build: .
#    depends_on:
#      - db
#      - redis
#    ports:
#      - 8080:8080